### ISSUE TITLE
Why not use free GitHub service of "https://"

### ISSUE THREAD

**Issue by sayemon10** [piratefsh/piratefsh.github.io#1]
![image](https://user-images.githubusercontent.com/35277447/64984160-00dae780-d8e4-11e9-9264-80ca75d08369.png)
to solve the problem, go to 
![image](https://user-images.githubusercontent.com/35277447/64984216-22d46a00-d8e4-11e9-9323-c5f61ad0ee9b.png)
&& enable this option 
![image](https://user-images.githubusercontent.com/35277447/64984255-3c75b180-d8e4-11e9-862c-0c0a9ce8de0b.png)

**Comment by piratefsh** [comment]
thanks for the tip! enabled.
